apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      registry: harbor.lab.randalllabs.com
      repository: containers/cert-manager-controller

    webhook:
      image:
        registry: harbor.lab.randalllabs.com
        repository: containers/cert-manager-webhook

    cainjector:
      image:
        registry: harbor.lab.randalllabs.com
        repository: containers/cert-manager-cainjector

    startupapicheck:
      image:
        registry: harbor.lab.randalllabs.com
        repository: containers/cert-manager-startupapicheck

    acmesolver:
      image:
        registry: harbor.lab.randalllabs.com
        repository: containers/cert-manager-acmesolver
