apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: rancher
spec:
  targetNamespace: cattle-system
  createNamespace: true
  insecureSkipTLSVerify: true
  chart: oci://harbor.lab.randalllabs.com/hauler/rancher
  version: 2.14.4
