apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: carbide-docs-system
  namespace: kube-system
spec:
  chart: oci://harbor.lab.randalllabs.com/hauler/airgapped-docs
  version: 0.1.54
  createNamespace: true
  insecureSkipTLSVerify: true
  targetNamespace: carbide-docs-system
  valuesContent: |-
    systemDefaultRegistry: https://harbor.lab.randalllabs.com
