---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
#---
#apiVersion: v1
#data:
#  cacerts.pem: 
#kind: Secret
#metadata:
#  name: tls-ca
#  namespace: cattle-system
#---
#apiVersion: v1
#data:
#  tls.crt: 
#  tls.key: 
#kind: Secret
#metadata:
#  name: tls-rancher-ingress
#  namespace: cattle-system
#type: kubernetes.io/tls
---
