apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rancher
  namespace: kube-system
spec:
  valuesContent: |-
    rancherImage: harbor.lab.randalllabs.com/rancher/rancher
    systemDefaultRegistry: harbor.lab.randalllabs.com
    hostname: mcm.lab.randalllabs.com
    bootstrapPassword: "admin"
    ingress:
      tls:
        source: "rancher"
    useBundledSystemChart: "true"
    extraEnv:
      - name: CATTLE_RKE_METADATA_CONFIG
        value: '{"refresh-interval-minutes":"0","url":"https://releases.rancher.com/kontainer-driver-metadata/release-2.14.2/data.json"}'
