---
- name: Add Repos for RHEL/CentOS/Rocky
  when:
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'
  block:
# Add RKE2 Common repo
  - name: Add the rke2-common repo RHEL/CentOS/Rocky
    ansible.builtin.yum_repository:
      name: "{{ rke2_common_yum_repo.name }}"
      description: "{{ rke2_common_yum_repo.description }}"
      baseurl: "{{ rke2_common_yum_repo.baseurl }}"
      gpgcheck: "{{ rke2_common_yum_repo.gpgcheck }}"
      gpgkey: "{{ rke2_common_yum_repo.gpgkey }}"
      enabled: "{{ rke2_common_yum_repo.enabled }}"
  
  # Add RKE2 versioned repo
  - name: Add the rke2 versioned repo CentOS/RHEL/Rocky
    ansible.builtin.yum_repository:
      name: "{{ rke2_versioned_yum_repo.name }}"
      description: "{{ rke2_versioned_yum_repo.description }}"
      baseurl: "{{ rke2_versioned_yum_repo.baseurl }}"
      gpgcheck: "{{ rke2_versioned_yum_repo.gpgcheck }}"
      gpgkey: "{{ rke2_versioned_yum_repo.gpgkey }}"
      enabled: "{{ rke2_versioned_yum_repo.enabled }}"

# - name: Debug install
#   ansible.builtin.debug:
#     msg: installing {{ service_name }}{{ rke2_version_rpm }}

- name: RKE2 Install
  ansible.builtin.shell:
    cmd: "transactional-update pkg install -y {{ service_name }}{{ rke2_version_rpm }}"
  register: result
  retries: 10
  until: result is succeeded
  delay: 30
  notify: "Restart {{ service_name }}"

- name: Reboot for transactional update to take effect
  ansible.builtin.reboot:
  
- name: Copy sysctl file
  ansible.builtin.copy:
    src: /usr/share/rke2/rke2-cis-sysctl.conf
    dest: /etc/sysctl.d/60-rke2-cis.conf
    mode: '0644'
    remote_src: true

