all:
  vars:
    rke2_install_version: v1.34.5+rke2r1
    local_archive_path: /opt/rancher/
    remote_archive_path: /opt/rancher/
    rke2_registry_config_file_path: "{{ playbook_dir }}/files/registries.yaml"
    cluster_rke2_config:
      selinux: true   
    rke2_common_yum_repo:
      name: "rancher-rke2-common-stable"
      description: "Rancher RKE2 Common stable"
      baseurl: "https://foreman.randalllabs.com/pulp/content/Randall_Labs/Library/custom/rke2/Rancher_RKE2_Common_stable_/"
      gpgcheck: false
      gpgkey: ""
      enabled: true
    
    rke2_versioned_yum_repo:
      name: "rancher-rke2-v{{ rke2_version_majmin }}"  # noqa jinja[spacing]
      description: "Rancher RKE2 Version"
      baseurl: "https://foreman.randalllabs.com/pulp/content/Randall_Labs/Library/custom/rke2/Rancher_RKE2_1_34_stable_/"
      gpgkey: ""
      gpgcheck: false
      enabled: true

rke2_cluster:
  children:
    rke2_servers:
      hosts:
        192.168.88.201:
        192.168.88.202:
        192.168.88.203:


